apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
  - name: api
    port: 8000
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: lapazcloud/microservices-api:staging
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: api-config
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: api-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: api-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-config
              key: POSTGRES_PASSWORD
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: api-config
              key: POSTGRES_PORT
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: api-config
              key: SECRET_KEY
        - name: DJANGO_DEBUG
          valueFrom:
            secretKeyRef:
              name: api-config
              key: DJANGO_DEBUG
