# Generated by Django 2.2.3 on 2019-08-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full Name', max_length=120)),
                ('address', models.CharField(help_text='Address', max_length=120)),
                ('email', models.CharField(help_text='Email address', max_length=120)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
